// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apyihnpqvhqnjyaqjjiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFweWlobnBxdmhxbmp5YXFqamlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczODMxMDEsImV4cCI6MjA2Mjk1OTEwMX0.8xfuBqYhTEFdMtebkoDcG2rbROFDak2SEYNWHXdkNzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);